# Generated by Django 5.1.7 on 2025-03-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(choices=[('charity', 'Charity'), ('retail', 'Retail'), ('service', 'service')], max_length=20),
        ),
    ]
