# Generated by Django 5.1.7 on 2025-03-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_website_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(choices=[('charity', 'Charity'), ('retail', 'Retail'), ('service', 'Service')], max_length=20),
        ),
    ]
